### ISSUE TITLE
Automatic installation fails

### ISSUE THREAD

**Issue by Velin92** [jamestut/awdlkiller#4]
Automatic installer fails:

```
nstalling awdlkiller ...
Copying '../awdlkiller' to '/usr/local/bin/awdlkiller' ...
Traceback (most recent call last):
  File "/Users/raumo/Documents/awdlkiller/misc/installer.py", line 140, in <module>
    sys.exit(main())
  File "/Users/raumo/Documents/awdlkiller/misc/installer.py", line 53, in main
    todo.do_install()
  File "/Users/raumo/Documents/awdlkiller/misc/installer.py", line 102, in do_install
    super().do_copyfile_setperm(f'../{cls.AWDLKILLER_NAME}', cls.AWDLKILLER_TARGET_PATH, cls.FMOD)
  File "/Users/raumo/Documents/awdlkiller/misc/installer.py", line 78, in do_copyfile_setperm
    shutil.copyfile(srcpath, targetpath)
  File "/Users/raumo/.pyenv/versions/3.10.14/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../awdlkiller'

```

**Comment by Velin92** [comment]
Solved, I was actually using the cloned repo instead of the release version
